# Generated by Django 3.0.5 on 2020-07-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroContrato', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('tipo', models.CharField(choices=[('1', 'Nome1'), ('2', 'Nome2'), ('3', 'Nome3')], max_length=1)),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Cancelado')], default='1', max_length=1)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to='files_contratos/')),
            ],
        ),
    ]
