# Generated by Django 3.0.5 on 2020-07-09 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='numeroContrato',
            new_name='numero_contrato',
        ),
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(upload_to='files_contratos_aditivos')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Contrato')),
            ],
        ),
    ]
